# Generated by Django 5.2.7 on 2025-11-19 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_city_university_type_user_gender_university_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city_id',
            new_name='bid',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='bname_ar',
        ),
        migrations.RenameField(
            model_name='college',
            old_name='collage_id',
            new_name='cid',
        ),
        migrations.RenameField(
            model_name='college',
            old_name='name',
            new_name='name_ar',
        ),
        migrations.RenameField(
            model_name='college',
            old_name='address',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='univer_id',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='name',
            new_name='uname_ar',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='address',
            new_name='uname_en',
        ),
        migrations.RemoveField(
            model_name='college',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='college',
            name='university',
        ),
        migrations.RemoveField(
            model_name='university',
            name='city',
        ),
        migrations.RemoveField(
            model_name='university',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='university',
            name='location',
        ),
        migrations.AddField(
            model_name='city',
            name='bname_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('ubid', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.ForeignKey(db_column='BID', on_delete=django.db.models.deletion.CASCADE, to='core.city')),
                ('university', models.ForeignKey(db_column='UID', on_delete=django.db.models.deletion.CASCADE, to='core.university')),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'unique_together': {('university', 'city')},
            },
        ),
        migrations.AddField(
            model_name='college',
            name='branch',
            field=models.ForeignKey(db_column='UBID', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.branch'),
        ),
    ]
