# Generated by Django 5.2.7 on 2025-12-20 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_systemsettings_academicaffiliation_college_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalrequest',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Approval Requests'},
        ),
        migrations.AlterModelOptions(
            name='notificationlog',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Notification Logs'},
        ),
        migrations.RenameField(
            model_name='approvalrequest',
            old_name='request_id',
            new_name='approval_id',
        ),
        migrations.RenameField(
            model_name='approvalrequest',
            old_name='comment',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='notificationlog',
            old_name='read',
            new_name='is_read',
        ),
        migrations.RenameField(
            model_name='notificationlog',
            old_name='log_id',
            new_name='notification_id',
        ),
        migrations.RenameField(
            model_name='systemsettings',
            old_name='value',
            new_name='setting_value',
        ),
        migrations.AlterUniqueTogether(
            name='approvalsequence',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='name',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='setting_id',
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='approval_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='approval_type',
            field=models.CharField(choices=[('project_proposal', 'مقترح مشروع'), ('student_transfer', 'نقل طالب'), ('group_transfer', 'نقل مجموعة'), ('external_project', 'مشروع خارجي'), ('co_supervisor', 'مشرف مشارك')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='current_approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='core.project'),
        ),
        migrations.AddField(
            model_name='approvalsequence',
            name='approval_levels',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='approvalsequence',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvalsequence',
            name='sequence_type',
            field=models.CharField(choices=[('single_department', 'مشروع قسم واحد'), ('multi_department', 'مشروع أقسام متعددة'), ('multi_college', 'مشروع كليات متعددة'), ('external', 'مشروع خارجي'), ('government', 'مشروع حكومي')], max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='is_sent_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('invitation', 'دعوة مجموعة'), ('approval', 'موافقة/رفض'), ('rejection', 'رفض'), ('transfer', 'نقل'), ('reminder', 'تذكير'), ('system', 'إشعار نظام'), ('message', 'رسالة')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='related_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.approvalrequest'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='related_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.group'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='related_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.project'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='related_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_about_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='title',
            field=models.CharField(default='not_mintioned', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='setting_key',
            field=models.CharField(default='n', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='academicaffiliation',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.university'),
        ),
        migrations.AlterField(
            model_name='academicaffiliation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='core.group'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('returned', 'مرجع للتعديل')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='branch',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.city'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.university'),
        ),
        migrations.AlterField(
            model_name='college',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.branch'),
        ),
        migrations.AlterField(
            model_name='department',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.college'),
        ),
        migrations.AlterField(
            model_name='group',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
        migrations.AlterField(
            model_name='groupmembers',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.group'),
        ),
        migrations.AlterField(
            model_name='groupmembers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupsupervisors',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.group'),
        ),
        migrations.AlterField(
            model_name='groupsupervisors',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='program',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.permission'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.role'),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.role'),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['recipient', '-created_at'], name='core_notifi_recipie_0a9596_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['is_read', 'recipient'], name='core_notifi_is_read_4166bb_idx'),
        ),
        migrations.RemoveField(
            model_name='approvalsequence',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='approvalsequence',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='approvalsequence',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='approvalsequence',
            name='group',
        ),
        migrations.RemoveField(
            model_name='approvalsequence',
            name='order',
        ),
    ]
