# Generated by Django 5.2.7 on 2025-12-23 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_approvalrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.college'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.CharField(choices=[('Completed', 'مكتمل'), ('Incomplete', 'غير مكتمل'), ('Reserved', 'محجوز'), ('Accepted', 'مقبول'), ('Rejected', 'مرفوض'), ('Pending', 'معلق')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('Government', 'مشاريع حكومية'), ('PrivateCompany', 'شركات خارجية'), ('ProposedProject', 'مشاريع مقترحة')], default='Government', max_length=100),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='setting_key',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='GroupCreationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('department_id', models.IntegerField()),
                ('college_id', models.IntegerField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_fully_confirmed', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMemberApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'طالب'), ('supervisor', 'مشرف'), ('co_supervisor', 'أستاذ مساعد')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('accepted', 'تمت الموافقة'), ('rejected', 'مرفوض')], default='pending', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='core.groupcreationrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('request', 'user')},
            },
        ),
    ]
