# Generated by Django 5.2.7 on 2025-12-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_project_college_alter_notificationlog_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalsequence',
            name='sequence_type',
            field=models.CharField(choices=[('single_department', 'مشروع قسم واحد'), ('multi_department', 'مشروع أقسام متعددة'), ('multi_college', 'مشروع كليات متعددة'), ('PrivateCompany', 'مشروع خارجي'), ('Government', 'مشروع حكومي')], max_length=50, null=True, unique=True),
        ),
    ]
