# Generated by Django 5.2.7 on 2025-12-31 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_approvalsequence_sequence_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalsequence',
            name='sequence_type',
            field=models.CharField(choices=[('single_department', 'مشروع قسم واحد'), ('multi_department', 'مشروع أقسام متعددة'), ('multi_college', 'مشروع كليات متعددة'), ('external', 'مشروع خارجي'), ('government', 'مشروع حكومي')], max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
    ]
